# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f863ed148f7a81701810b93dadd4690961efbaaaa16aa4e5163323468ac7df31be3bc4e34870bc3e9fd79d5afec12a667992d400361635f0c66078c0d57e22b6

test:
  secret_key_base: 6fa284109148a5dadd243bdba48508a2f3d039f061589180a20434c34abb2a8b7db2044c50a7218e04073e3764663669eb219c850f0b997d94e2f2fdc50e52bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
